<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 3/31/2020
 * Time: 3:14 PM
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class Imagerie extends Model
{
    protected $table = "imagerie";
    public $id, $nom, $nom_alternatif, $id_categorie, $prix, $cout, $devise, $principale;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getNomAlternatif()
    {
        return $this->nom_alternatif;
    }

    /**
     * @param mixed $nom_alternatif
     */
    public function setNomAlternatif($nom_alternatif)
    {
        $this->nom_alternatif = $nom_alternatif;
    }

    /**
     * @return mixed
     */
    public function getIdCategorie()
    {
        return $this->id_categorie;
    }

    /**
     * @param mixed $id_categorie
     */
    public function setIdCategorie($id_categorie)
    {
        $this->id_categorie = $id_categorie;
    }

    /**
     * @return mixed
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * @param mixed $prix
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;
    }

    /**
     * @return mixed
     */
    public function getCout()
    {
        return $this->cout;
    }

    /**
     * @param mixed $cout
     */
    public function setCout($cout)
    {
        $this->cout = $cout;
    }

    /**
     * @return mixed
     */
    public function getDevise()
    {
        return $this->devise;
    }

    /**
     * @param mixed $devise
     */
    public function setDevise($devise)
    {
        $this->devise = $devise;
    }

    /**
     * @return mixed
     */
    public function getPrincipale()
    {
        return $this->principale;
    }

    /**
     * @param mixed $principale
     */
    public function setPrincipale($principale)
    {
        $this->principale = $principale;
    }


    private function existe($nom){
        try{
            $con=self::connection();
            $req="select *from imagerie where nom=:nom";
            $stmt=$con->prepare($req);
            $stmt->execute(array(
                ":nom"=>$nom
            ));
            $data=$stmt->fetchAll();
            if(count($data)>0){
                return true;
            }
            return false;
        }catch (\Exception $ex){
            throw new \Exception($ex->getMessage());
        }
    }

    public function findByNom($nom){
        $con=self::connection();
        $req="select *from imagerie where nom=:nom";
        $stmt=$con->prepare($req);
        $stmt->execute(array(
            ":nom"=>$nom
        ));
        $data=$stmt->fetchAll(\PDO::FETCH_OBJ);
        if(count($data)>0){
            return $data[0];
        }
        return null;
    }

    public function add()
    {
        if($this->existe($this->nom)){
            return "Catégorie examens existe deja";

        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public static function idLaboratoire($nom)
    {
        $con = self::connection();
        try {
            $req = "SELECT id FROM imagerie WHERE nom='" . $nom . "'";
            $rs = $con->query($req);
            $data = $rs->fetch();
            return $data['id'];
        } catch (\Exception $ex) {
            return $ex->getMessage();
        }
    }


}
