<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 4/8/2020
 * Time: 12:14 PM
 */

namespace app\DefaultApp\Models;
use systeme\Model\Model;

class Patient extends Model
{
    public $id, $code, $nom, $prenom,$email,$date_naissance, $sexe,$telephone,$password,$no_identite;
    public $balance;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom): void
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * @param mixed $sexe
     */
    public function setSexe($sexe): void
    {
        $this->sexe = $sexe;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone): void
    {
        $this->telephone = $telephone;
    }

    public function existe2($no_identite)
    {
        $con = self::connection();
        $req = "SELECT *FROM patient WHERE no_identite='{$no_identite}' ";
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            return true;
        } else {
            return false;
        }

    }


    public function existe($nom, $prenom)
    {
        $con = self::connection();
        $req = "SELECT *FROM patient WHERE (nom='" . $nom . "' and prenom='" . $prenom . "' )";
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            return true;
        } else {
            return false;
        }

    }

    public function cashExiste($nom, $prenom, $telephone)
    {
        $con = self::connection();
        $req = "SELECT *FROM patient WHERE nom='{$nom}' and prenom='{$prenom}' and telephone='{$telephone}'";
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            return true;
        } else {
            return false;
        }

    }


    public static function dernierId()
    {
        $con = self::connection();
        $req = "select id from patient order by id desc LIMIT 1";
        $rs = $con->query($req);
        $data = $rs->fetch();
        return $data['id'];

    }

    public function add()
    {

        if($this->existe2($this->no_identite)){
            return "No identite existe";
        }

        if ($this->existe($this->nom, $this->prenom)) {
            return "Patient Existe";
        }

        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function add1(){
        return parent::add();
    }

    public static function serviceEncour($id_patient, $id_service)
    {
        $con = self::connection();
        $nomService = Service::nonService($id_service);
        if ($nomService == "SSC") {
            $req = "select *from admision WHERE (id_patient='" . $id_patient . "' and service_actuel='" . $id_service . "' and statut='en cour' and statut_intervention='enregistrer') or  (id_patient='" . $id_patient . "' and admis_via='" . $id_service . "' and statut='en cour' and statut_intervention='enregistrer') ";

        } else {
            $req = "select *from admision WHERE (id_patient='" . $id_patient . "' and service_actuel='" . $id_service . "' and statut='en cour') or  (id_patient='" . $id_patient . "' and admis_via='" . $id_service . "' and statut='en cour') ";

        }
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            return true;
        } else {
            return false;
        }

    }

    public static function idPatient($code)
    {
        $con = self::connection();
        $req = "SELECT *FROM patient WHERE code='" . $code . "'";
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            $con = null;
            return $data['id'];
        } else {
            $con = null;
            return "";
        }
    }

    public static function prefixCode(){
        return "B-";
    }

    public static function codePatient()
    {
        return self::num_patient_suivant();
    }

    public static function num_patient_suivant()
    {
        $con = self::connection();
        $req = "SELECT numero_patient FROM numero_patient ORDER BY numero_patient DESC LIMIT 1";
        $rs = $con->query($req);
        $data = $rs->fetch();
        if(is_array($data)) {
            $numero = $data['numero_patient'];
        }else{
            $numero=-1;
        }
        $n = $numero + 1;
        return $n;
    }

    public static function incrementNumber(){
        $n=self::codePatient();
        $con=self::connection();
        $req2 = "INSERT INTO numero_patient VALUES ('" . $n . "')";
        $con->query($req2);
    }

    public static function total(){
        $bdd=self::connection();
        $total = $bdd->query('SELECT * FROM patient');
        return $total->rowCount();
    }

    public static function dixDernier(){
        $con=self::connection();
        $req="select *from patient order by id desc limit 5";
        $stmt=$con->prepare($req);
        $stmt->execute();
        return $stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
    }

    public function listeHopital(){
        $con=self::connection();
        $req="select *from patient where type='hopital'";
        $stmt=$con->prepare($req);
        $stmt->execute();
        return $stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
    }

    public function listeChl(){
        $con=self::connection();
        $req="select *from patient where type='chl'";
        $stmt=$con->prepare($req);
        $stmt->execute();
        return $stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
    }


    public static function connecter($user_name, $password)
    {
        $password = md5($password);
        try {
            $con = self::connection();
            $req = "SELECT *FROM patient WHERE (email=:pseudo AND password=:password) or (telephone=:pseudo and password=:password)";
            $stmt = $con->prepare($req);
            $stmt->execute(array(
                ":pseudo" => $user_name,
                ":password" => $password
            ));
            $data = $stmt->fetchAll(\PDO::FETCH_OBJ);
            if (count($data) > 0) {
                $_SESSION['utilisateur'] = $data[0]->id;
                $_SESSION['pseudo'] = $data[0]->email;
                $_SESSION['role'] = "patient";
                return "ok";
            } else {
                return "pseudo ou motdepasse incorect";
            }
        } catch (\Exception $ex) {
            throw new \Exception($ex->getMessage());
        }
    }



}
