<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 3/26/2020
 * Time: 6:57 PM
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class PersonelMedical extends Model
{

    protected $table="personel_medical";
    public $id,$nom,$prenom;
    public $telephone,$email,$password,$specialiter,$type;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom): void
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * @param mixed $sexe
     */
    public function setSexe($sexe): void
    {
        $this->sexe = $sexe;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone): void
    {
        $this->telephone = $telephone;
    }

    /**
     * @return mixed
     */
    public function getIdentifiant()
    {
        return $this->identifiant;
    }

    /**
     * @param mixed $identifiant
     */
    public function setIdentifiant($identifiant): void
    {
        $this->identifiant = $identifiant;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void
    {
        $this->password = $password;
    }




    public function existe($nom,$prenom)
    {
        $con=self::connection();
        $req = "SELECT *FROM personel_medical WHERE nom='".$nom."' and prenom='".$prenom."'";
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            return true;
        } else {
            return false;
        }

    }


    public function add()
    {
        if($this->existe($this->nom,$this->prenom)){
            return "Personel Médical existe";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public static function activer($id)
    {
        $con=self::connection();
        $req = "UPDATE personel_medical SET actif='oui' WHERE id='" . $id . "'";
        $con->query($req);
    }

    public static function desactiver($id)
    {
        $con=self::connection();
        $req = "UPDATE personel_medical SET actif='non' WHERE id='" . $id . "'";
        $con->query($req);
    }

    public static function idPersonel($nom,$prenom)
    {
        $con = self::connection();
        $req = "select id From personel_medical where nom='{$nom}' and prenom='{$prenom}' ";
        $rs = $con->query($req);
        $data = $rs->fetch();
        return $data['id'];
    }

    public static function total(){
        $bdd=self::connection();
        $total = $bdd->query('SELECT * FROM personel_medical');
        return $total->rowCount();
    }

    public function listerMedecin()
    {
        $con=self::connection();
        $req="select *from personel_medical where type='médecin'";
        $stmt=$con->prepare($req);
        $stmt->execute();
        return $stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
    }

    public function listerMedecinRadiologue()
    {
        $con=self::connection();
        $req="select *from personel_medical where type='médecin radiologue'";
        $stmt=$con->prepare($req);
        $stmt->execute();
        return $stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
    }

    public static function connecter($user_name, $password)
    {
        $password = md5($password);
        try {
            $con = self::connection();
            $req = "SELECT *FROM personel_medical WHERE email=:pseudo AND password=:password";
            $stmt = $con->prepare($req);
            $stmt->execute(array(
                ":pseudo" => $user_name,
                ":password" => $password
            ));
            $data = $stmt->fetchAll(\PDO::FETCH_OBJ);
            if (count($data) > 0) {
                $id_session = md5(sha1(uniqid('', true)));
                $_SESSION['utilisateur'] = $data[0]->id;
                $_SESSION['pseudo'] = $data[0]->email;
                $_SESSION['role'] = $data[0]->type;
                $_SESSION['id_session'] = $id_session;
                return "ok";
            } else {
                return "pseudo ou motdepasse incorect";
            }
        } catch (\Exception $ex) {
            throw new \Exception($ex->getMessage());
        }
    }

}
