<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 3/26/2020
 * Time: 6:57 PM
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class PersonelMedical extends Model
{

    protected $table="personel_medical";
    public $id,$nom,$prenom;
    public $telephone,$identifiant,$password;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom): void
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * @param mixed $sexe
     */
    public function setSexe($sexe): void
    {
        $this->sexe = $sexe;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone): void
    {
        $this->telephone = $telephone;
    }

    /**
     * @return mixed
     */
    public function getIdentifiant()
    {
        return $this->identifiant;
    }

    /**
     * @param mixed $identifiant
     */
    public function setIdentifiant($identifiant): void
    {
        $this->identifiant = $identifiant;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void
    {
        $this->password = $password;
    }




    public function existe($nom,$prenom,$licence)
    {
        $con=self::connection();
        $req = "SELECT *FROM personel_medical WHERE nom='".$nom."' and prenom='".$prenom."' and licence='" . $licence . "'";
        $rs = $con->query($req);
        if ($data = $rs->fetch()) {
            return true;
        } else {
            return false;
        }

    }


    public function add()
    {
        if($this->existe($this->nom,$this->prenom,$this->licence)){
            return "Personel Médical existe";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public static function activer($id)
    {
        $con=self::connection();
        $req = "UPDATE personel_medical SET actif='oui' WHERE id='" . $id . "'";
        $con->query($req);
    }

    public static function desactiver($id)
    {
        $con=self::connection();
        $req = "UPDATE personel_medical SET actif='non' WHERE id='" . $id . "'";
        $con->query($req);
    }

    public static function idPersonel($nom,$prenom)
    {
        $con = self::connection();
        $req = "select id From personel_medical where nom='{$nom}' and prenom='{$prenom}' ";
        $rs = $con->query($req);
        $data = $rs->fetch();
        return $data['id'];
    }

    public static function connecter($critere, $motdepasse)
    {
        try {
            date_default_timezone_set("America/Port-au-Prince");
            $con = self::connection();
            $motdepasse = sha1($motdepasse);
            $req = "SELECT *FROM personel_medical WHERE  identifiant=:critere AND password=:motdepasse";
            $stmt = $con->prepare($req);
            $param = array(
                ":critere" => $critere,
                ":motdepasse" => $motdepasse
            );
            $stmt->execute($param);
            if ($data = $stmt->fetch()) {

                if($data['actif']==="non"){
                    return "votre compte est inactif, contacter l'administrateur";
                }
                $id_session = md5(sha1(uniqid('', true)));
                $re = "UPDATE personel_medical SET statut='1',id_session='" . $id_session . "' WHERE id='" . $data['id'] . "'";
                self::connection()->query($re);
                $_SESSION['utilisateur'] = $data['id'];
                $_SESSION['pseudo'] = $data['identifiant'];
                $_SESSION['role'] = $data['role'];
                $_SESSION['id_session'] = $id_session;
                $cookie_name = "conn";
                $cookie_value = 'oui';
                setcookie($cookie_name, $cookie_value, time() + (86400 * 365), "/", "", true, true); // 86400 = 1 day
                return "ok";

            } else {
                return "pseudo ou motdepasse incorect";
            }
        } catch (\Exception $ex) {
            throw new \Exception($ex->getMessage());
        }

    }

    public static function total(){
        $bdd=self::connection();
        $total = $bdd->query('SELECT * FROM personel_medical');
        return $total->rowCount();
    }


}
